x-TZ: &TZ "Asia/Tokyo"

services:
  app:
    build:
      context: ../
      target: builder
    command: sleep infinity
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /work
    environment:
      TZ: *TZ
    env_file:
      - path: devcontainer.env
        required: false

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    links:
      - "app:app"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    environment:
      TZ: *TZ
